Update Jenkinsfile02

diff --git a/Jenkinsfile02 b/Jenkinsfile02
--- a/Jenkinsfile02
+++ b/Jenkinsfile02
@@ -11,6 +11,7 @@ pipeline {
                 script {
                     // Update the package manager and install AWS CLI and kubectl
                     sh '''
+                    set -e  # Exit immediately if a command exits with a non-zero status
                     yum update -y
                     yum install -y aws-cli
 
@@ -36,21 +37,17 @@ pipeline {
                 script {
                     // Use the withCredentials block to access AWS credentials
                     withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-cred']]) {
-                        // Set AWS environment variables
+                        // Set AWS environment variables automatically
                         sh '''
-                        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
-                        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                         export AWS_DEFAULT_REGION=ap-southeast-2  # Change to your desired region
-                        '''
-                        
-                        // Update kubeconfig to connect to the EKS cluster
-                        sh '''
-                        aws eks update-kubeconfig --name stg-eks --region ap-southeast-2
+                        aws eks update-kubeconfig --name stg-eks --region $AWS_DEFAULT_REGION
                         '''
                         
                         // Check the kubeconfig file and update the apiVersion if necessary
-                        sed -i 's/apiVersion: client.authentication.k8s.io/v1alpha1/apiVersion: client.authentication.k8s.io\/v1beta1/g' ~/.kube/config || true
-                        sed -i 's/apiVersion: client.authentication.k8s.io/v1beta1/apiVersion: client.authentication.k8s.io\/v1beta1/g' ~/.kube/config || true
+                        if [ -f ~/.kube/config ]; then
+                            sed -i 's/apiVersion: client.authentication.k8s.io/v1alpha1/apiVersion: client.authentication.k8s.io\/v1beta1/g' ~/.kube/config || true
+                            sed -i 's/apiVersion: client.authentication.k8s.io/v1beta1/apiVersion: client.authentication.k8s.io\/v1beta1/g' ~/.kube/config || true
+                        fi
                         
                         // Optionally, you can run a kubectl command to verify the connection
                         sh 'kubectl get nodes'
